PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Controllers/AdminQLSanPhamController.cs
using PS36400_NguyenLocThong_Assignment.Models;
using PS36400_NguyenLocThong_Assignment.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList;
using System.Reflection.PortableExecutable;
using System.Runtime.Intrinsics.Arm;

namespace PS36400_NguyenLocThong_Assignment.Areas.Admin.Controllers
{
    [Area("AdminPage")]
    [Route("Admin/{controller}/{action}")]
    public class AdminQLSanPhamController : Controller
    {
        private readonly MobilePhoneContext db;
        private readonly IWebHostEnvironment environment;
        public AdminQLSanPhamController(MobilePhoneContext context, IWebHostEnvironment environment)
        {
            this.environment = environment;
            this.db = context;
        }
        public IActionResult IndexSP(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            // Lấy danh sách sản phẩm từ database
            var sanPhams = db.SanPhams.ToList();

            // Chia danh sách sản phẩm thành các trang
            var pagedSanPhams = sanPhams.ToPagedList(pageNumber, pageSize);

            return View(pagedSanPhams);
        }

        [HttpGet]
        public IActionResult CreateSP()
        {
            ViewBag.MaLoaiSp = new SelectList(db.LoaiSanPhams, "MaLoaiSp", "TenLoaiSp");
            return View();
        }

        [HttpPost]
        public IActionResult CreateSP(SanphamVM sp)   
        {
            if(sp.HinhSp == null)
            {
                ModelState.AddModelError("HinhSp", "*Ảnh sản phẩm không được bỏ trống");
            }
            if (!ModelState.IsValid)
            {
                return View(sp);
            }

            string newFileName = Path.GetFileName(sp.HinhSp.FileName);

            string imageFullPath = environment.WebRootPath + "/image/" + newFileName;
            using(var stream = System.IO.File.Create(imageFullPath))
            {
                sp.HinhSp.CopyTo(stream);
            }

            SanPham sanPham = new SanPham()
            {
                TenSp = sp.TenSp,
                GiaSp = sp.GiaSp,
                HinhSp = newFileName,
                Chip = sp.Chip,
                ManHinh = sp.ManHinh,
                Ram = sp.Ram,
                Rom = sp.Rom,
                Soluotban = sp.Soluotban,
                NgaydangSp = DateTime.Now,
                MaLoaiSp = sp.MaLoaiSp
            };

            db.SanPhams.Add(sanPham);
            db.SaveChanges();

            return RedirectToAction("IndexSP");
        }

        [HttpGet]
        public IActionResult EditSP(int id)
        {
            var sp = db.SanPhams.Find(id);

            if(sp == null)
            {
                return RedirectToAction("IndexSP");
            }

            var spVM = new SanphamVM()
            {
                TenSp = sp.TenSp,
                GiaSp = sp.GiaSp,
                Chip = sp.Chip,
                ManHinh = sp.ManHinh,
                Ram = sp.Ram,
                Rom = sp.Rom,
                Soluotban = sp.Soluotban,
                MaLoaiSp = sp.MaLoaiSp
            };

            ViewBag.MaLoaiSp = new SelectList(db.LoaiSanPhams, "MaLoaiSp", "TenLoaiSp");
            ViewData["MaSP"] = sp.MaSp;
            ViewData["HinhSP"] = sp.HinhSp; 
            ViewData["NgayDangSP"] = sp.NgaydangSp;

            return View(spVM);
        }

        [HttpPost]
        public IActionResult EditSP(int id, SanphamVM spVM)
        {
            var sp = db.SanPhams.Find(id);

            if (sp == null)
            {
                return RedirectToAction("IndexSP");
            }

            if(!ModelState.IsValid)
            {
                ViewBag.MaLoaiSp = new SelectList(db.LoaiSanPhams, "MaLoaiSp", "TenLoaiSp");
                ViewData["MaSP"] = sp.MaSp;
                ViewData["HinhSP"] = sp.HinhSp;
                ViewData["NgayDangSP"] = sp.NgaydangSp;

                return View(spVM);
            }

            // upload ảnh mới
            string newFileName = sp.HinhSp;

            if (spVM.HinhSp != null)
            {
                newFileName = Path.GetFileName(spVM.HinhSp.FileName);

                string imageFullPath = environment.WebRootPath + "/image/" + newFileName;
                using (var stream = System.IO.File.Create(imageFullPath))
                {
                    spVM.HinhSp.CopyTo(stream);
                }

                string oldHinhFullPath = environment.WebRootPath + "/image/" + sp.HinhSp;
                System.IO.File.Delete(oldHinhFullPath);
            }

            sp.TenSp = spVM.TenSp;
            sp.GiaSp = spVM.GiaSp;
            sp.HinhSp = newFileName;
            sp.Chip = spVM.Chip;
            sp.ManHinh = spVM.ManHinh;
            sp.Ram = spVM.Ram;
            sp.Rom = spVM.Rom;
            sp.MaLoaiSp = spVM.MaLoaiSp;

            db.SaveChanges();

            return RedirectToAction("IndexSP");
        }

        public IActionResult DeleteSP(int id)
        {
            var sp = db.SanPhams.Find(id);

            if (sp == null)
            {
                return RedirectToAction("IndexSP");
            }

            string imageFullPath = environment.WebRootPath + "/image/" + sp.HinhSp;
            System.IO.File.Delete(imageFullPath);

            db.SanPhams.Remove(sp);
            db.SaveChanges();

            return RedirectToAction("IndexSP");
        }
    }
}

PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Views/AdminQLSanPham/CreateSP.cshtml
@model PS36400_NguyenLocThong_Assignment.ViewModels.SanphamVM

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_Layout.cshtml";
}

<h1>Thêm mới sản phẩm</h1>
<a asp-action="IndexSP" asp-controller="AdminQLSanPham" class="btn btn-danger">Trở về</a>

<hr />
<div class="row">
    <div class="col-md-6 mx-auto">
        <form asp-action="CreateSP" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="form-group col-md-6">
                    Tên sản phẩm
                    <input asp-for="TenSp" class="form-control" />
                    <span asp-validation-for="TenSp" class="text-danger"></span>
                        </div>
                <div class="form-group col-md-6">
                    Giá sản phẩm
                    <input asp-for="GiaSp" class="form-control" />
                    <span asp-validation-for="GiaSp" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                Ảnh sản phẩm
                <input asp-for="HinhSp" class="form-control" />
                <span asp-validation-for="HinhSp" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    Chip
                    <input asp-for="Chip" class="form-control" />
                    <span asp-validation-for="Chip" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    Kích thước màn hình
                    <input asp-for="ManHinh" class="form-control" />
                    <span asp-validation-for="ManHinh" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    Ram
                    <input asp-for="Ram" class="form-control" />
                    <span asp-validation-for="Ram" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    Rom
                    <input asp-for="Rom" class="form-control" />
                    <span asp-validation-for="Rom" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                Số lượt bán
                <input asp-for="Soluotban" readonly value="0" class="form-control" />
                <span asp-validation-for="Soluotban" class="text-danger"></span>
            </div>
            <div class="form-group">
                Ngày đăng sản phẩm
                <input asp-for="NgaydangSp" class="form-control" />
                <span asp-validation-for="NgaydangSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                Tên loại sản phẩm
                <select asp-for="MaLoaiSp" class ="form-control" asp-items="ViewBag.MaLoaiSp"></select>
            </div>
            <div class="form-group">
                <button class="btn btn-primary mb-4 float-right" type="submit">Thêm</button>
            </div>
        </form>
    </div>
</div>

PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Views/AdminQLSanPham/EditSP.cshtml
@model PS36400_NguyenLocThong_Assignment.ViewModels.SanphamVM;

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_Layout.cshtml";
}

<h1>Cập Nhật Sản Phẩm</h1>
<div>
    <a asp-action="IndexSP" asp-controller="AdminQLSanPham" class="btn btn-danger">Trở về</a>
</div>
<hr />
<div class="row">
    <div class="col-md-6 mx-auto">
        <form method="post" enctype="multipart/form-data">
            <input type="hidden" name="id" value="@ViewData["MaSP"]" />
            <div class="row">
                <div class="form-group col-md-6">
                    Tên sản phẩm
                    <input asp-for="TenSp" class="form-control" />
                </div>
                <div class="form-group col-md-6">
                    Giá sản phẩm
                    <input asp-for="GiaSp" class="form-control" />
                    <span asp-validation-for="GiaSp" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="offset-sm-4 col-sm-6">
                    <img src="/image/@ViewData["HinhSP"]" width="150">
                </div>
            </div>
            <div class="form-group">
                Hình sản phẩm
                <input asp-for="HinhSp" class="form-control" />
                <span asp-validation-for="HinhSp" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    Chip
                    <input asp-for="Chip" class="form-control" />
                    <span asp-validation-for="Chip" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    Màn hình
                    <input asp-for="ManHinh" class="form-control" />
                    <span asp-validation-for="ManHinh" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    Ram
                    <input asp-for="Ram" class="form-control" />
                    <span asp-validation-for="Ram" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    Rom
                    <input asp-for="Rom" class="form-control" />
                    <span asp-validation-for="Rom" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                Số lượt bán
                <input asp-for="Soluotban" readonly class="form-control" />
            </div>
            <div class="form-group">
                Ngày đăng sản phẩm
                <input value="@ViewData["NgayDangSP"]" readonly class="form-control" />
            </div>
            <div class="form-group">
                Tên loại sản phẩm
                <select asp-for="MaLoaiSp" class="form-control" asp-items="ViewBag.MaLoaiSp"></select>
                <span asp-validation-for="MaLoaiSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button class="btn btn-primary mr-1" type="submit">Sửa</button>
            </div>
        </form>
    </div>
</div>

PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Views/AdminQLSanPham/IndexSP.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminPage/Views/Shared/_Layout.cshtml";
}


@model PagedList.IPagedList<PS36400_NguyenLocThong_Assignment.Models.SanPham>
@using PagedList.Mvc;

<div class="section-body">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h2>Quản Lí Sản Phẩm</h2>
            </div>
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-12 col-md-12">
                        <a asp-action="CreateSP" asp-controller="AdminQLSanPham" class="btn btn-primary">Thêm sản phẩm mới</a>
                    </div>
                </div>
                <table class="table" id="product-table">
                    <thead>
                        <tr style="text-align: center;">
                            <th scope="col">Mã sản phẩm</th>
                            <th scope="col">Tên Sản Phẩm</th>
                            <th scope="col">Giá</th>
                            <th scope="col">Hình</th>
                            <th scope="col">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr style="text-align: center;">
                                <th scope="row">@item.MaSp</th>
                                <td>@item.TenSp</td>
                                <td>@String.Format("{0:N0}", item.GiaSp)đ</td>
                                <td><img src="~/image/@item.HinhSp" width="100px" style="padding:15px" /></td>
                                <td>
                                    <a asp-action="EditSP" asp-controller="AdminQLSanPham" asp-route-id="@item.MaSp" class="btn btn-primary">Sửa</a>
                                    <a asp-action="DeleteSP" asp-controller="AdminQLSanPham" asp-route-id="@item.MaSp" class="btn btn-danger">Xóa</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="card-body">
                    <nav style="float: right;">
                        <ul class="pagination">
                            @if (Model.HasPreviousPage)
                            {
                                <li class="page-item">
                                    <a class="page-link" asp-controller="AdminQLSanPham" asp-action="IndexSP" asp-route-page="@(Model.PageNumber - 1)">Trước</a>
                                </li>
                            }
                            else
                            {
                                <li class="page-item disabled">
                                    <a class="page-link">Trước</a>
                                </li>
                            }
                            @for (int i = 1; i <= Model.PageCount; i++)
                            {
                                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                                    <a class="page-link" asp-controller="AdminQLSanPham" asp-action="IndexSP" asp-route-page="@i">@i</a>
                                </li>
                            }
                            @if (Model.HasNextPage)
                            {
                                <li class="page-item">
                                    <a class="page-link" asp-controller="AdminQLSanPham" asp-action="IndexSP" asp-route-page="@(Model.PageNumber + 1)">Sau</a>
                                </li>
                            }
                            else
                            {
                                <li class="page-item disabled">
                                    <a class="page-link">Sau</a>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>