PS36400_NguyenLocThong_Assignment/Controllers/DanhMucSPController.cs
using PS36400_NguyenLocThong_Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PagedList;
using System.Collections.Generic;
using System.Drawing.Printing;

namespace _21_PS36400_NguyenLocThong_ASM.Controllers
{
    public class DanhMucSPController : Controller
    {
        private readonly MobilePhoneContext db;
        public DanhMucSPController(MobilePhoneContext context)
        {
            db = context;
        }


        // Danh mục sản phẩm
        public IActionResult Index(string loai, int? id, string sortOrder, string priceRange, string screenSize,int page = 1, int pageSize = 6)
        {
            var listsp = db.SanPhams.AsQueryable();

            // Tìm MaLoaiSp tương ứng với tên loại sản phẩm
            if (!string.IsNullOrEmpty(loai))
            {
                var loaiSp = db.LoaiSanPhams.FirstOrDefault(x => x.TenLoaiSp == loai);
                if (loaiSp != null)
                {
                    id = loaiSp.MaLoaiSp;
                }
            }

            // Lọc sản phẩm theo MaLoaiSp
            if (id.HasValue)
            {
                listsp = listsp.Where(x => x.MaLoaiSp == id.Value);
            }


            ViewBag.SortNewSP = string.IsNullOrEmpty(sortOrder) ? "sanphammoi" : "sanphammoi";
            ViewBag.SortBestSeller = (sortOrder == "sanphambanchay" ? "sanphambanchay" : "sanphambanchay");
            ViewBag.SortPriceUp = (sortOrder == "giatang" ? "giatang" : "giatang");
            ViewBag.SortPriceDown = (sortOrder == "giagiam" ? "giagiam" : "giagiam");

            // Sắp xếp sản phẩm
            switch (sortOrder)
            {
                case "sanphammoi":
                    listsp = listsp.OrderByDescending(x => x.NgaydangSp);
                    break;
                case "sanphambanchay":
                    listsp = listsp.OrderByDescending(x => x.Soluotban);
                    break;
                case "giatang":
                    listsp = listsp.OrderBy(x => x.GiaSp);
                    break;
                case "giagiam":
                    listsp = listsp.OrderByDescending(x => x.GiaSp);
                    break;
                default:
                    listsp = listsp.OrderByDescending(x => x.NgaydangSp);
                    break;
            }

            // Lọc sản phẩm theo giá
            switch (priceRange)
            {
                case "down2Mil":
                    listsp = listsp.Where(x => x.GiaSp < 2000000);
                    break;
                case "2to4Mil":
                    listsp = listsp.Where(x => x.GiaSp >= 2000000 && x.GiaSp < 4000000);
                    break;
                case "4to7Mil":
                    listsp = listsp.Where(x => x.GiaSp >= 4000000 && x.GiaSp < 7000000);
                    break;
                case "up7Mil":
                    listsp = listsp.Where(x => x.GiaSp >= 7000000);
                    break;
                default:
                    break;
            }

            // Lọc sản phẩm theo kích thước màn hình
            switch (screenSize)
            {
                case "6den7inches":
                    listsp = listsp.Where(x => x.ManHinh >= 6 && x.ManHinh <= 7);
                    break;
                case "tren7inches":
                    listsp = listsp.Where(x => x.ManHinh > 7 || x.ManHinh == null);
                    break;
                default:
                    break;
            }

            var result = listsp.Select(x => new SanPham
            {
                MaSp = x.MaSp,
                HinhSp = x.HinhSp,
                TenSp = x.TenSp,
                GiaSp = x.GiaSp,
                Chip = x.Chip,
                ManHinh = x.ManHinh,
                Ram = x.Ram,
                Rom = x.Rom
            }).ToPagedList(page, pageSize);

            // Truyền tham số maloai vào view data để sử dụng trong view
            ViewData["TenLoai"] = loai;
            ViewData["SortOrder"] = sortOrder;
            ViewData["PriceRange"] = priceRange;
            ViewData["ScreenSize"] = screenSize;

            return View(result);
        }

        // Sản phẩm chi tiết
        public async Task<IActionResult> DetailProduct(int id)
        {
            var productDetail = await db.SanPhams.FirstOrDefaultAsync(p => p.MaSp == id);

            return View(productDetail);
        }


        // Phương thức cập nhật số lượt bán của sản phẩm
        public void UpdateProductSales(int productId, int quantity)
        {
            var product = db.SanPhams.Find(productId);
            if (product != null)
            {
                product.Soluotban += quantity;
                db.SaveChanges();
            }
        }

    }


}

PS36400_NguyenLocThong_Assignment/Controllers/RegisterController.cs
using PS36400_NguyenLocThong_Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography;
using System.Text;

namespace PS36400_NguyenLocThong_Assignment
{
    public class RegisterController : Controller
    {
        private readonly MobilePhoneContext db;

        public RegisterController(MobilePhoneContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(NguoiDung model)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem email đã được sử dụng chưa
                var existingUser = db.NguoiDungs.FirstOrDefault(u => u.Email == model.Email);
                if (existingUser != null)
                {
                    ModelState.AddModelError("Email", "Email đã được sử dụng");
                    return View();
                }

                // Mã hóa mật khẩu trước khi lưu vào cơ sở dữ liệu
                model.MatKhau = HashPassword(model.MatKhau);

                // Lưu thông tin người dùng vào cơ sở dữ liệu
                db.NguoiDungs.Add(model);
                db.SaveChanges();

                // Chuyển hướng đến trang đăng nhập sau khi đăng ký thành công
                return RedirectToAction("Index", "Login");
            }

            // Nếu dữ liệu không hợp lệ, hiển thị lại trang đăng ký với thông báo lỗi
            return View();
        }

        // Hàm mã hóa mật khẩu sử dụng SHA256
        private string HashPassword(string password)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < hashedBytes.Length; i++)
                {
                    builder.Append(hashedBytes[i].ToString("x2"));
                }
                return builder.ToString();
            }
        }
    }
}

PS36400_NguyenLocThong_Assignment/Controllers/TimKiemSPController.cs
using Microsoft.AspNetCore.Mvc;
using PS36400_NguyenLocThong_Assignment.Models;

namespace _21_PS36400_NguyenLocThong_ASM.Controllers
{
    public class TimKiemSPController : Controller
    {
        private readonly MobilePhoneContext db;
        public TimKiemSPController(MobilePhoneContext context)
        {
            db = context;
        }
        public IActionResult Index(string timkiem)
        {
            var listsp = db.SanPhams.AsQueryable();


            if (string.IsNullOrEmpty(timkiem))
            {
                ViewBag.NullQuery = "Không tìm thấy sản phẩm bạn tìm";
                return View();
            }

            listsp = listsp.Where(x => x.TenSp.Contains(timkiem));


            var result = listsp.Select(x => new SanPham
            {
                MaSp = x.MaSp,
                HinhSp = x.HinhSp,
                TenSp = x.TenSp,
                GiaSp = x.GiaSp,
                Chip = x.Chip,
                ManHinh = x.ManHinh,
                Ram = x.Ram,
                Rom = x.Rom
            });
            ViewBag.Query = timkiem;

            if (!result.Any())
            {
                ViewBag.NullQuery = "Không tìm thấy sản phẩm bạn cần tìm";
                return View();
            }

            return View(result);
        }
    }
}

PS36400_NguyenLocThong_Assignment/Controllers/TrangChuController.cs
using PS36400_NguyenLocThong_Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;

namespace PS36400_NguyenLocThong_Assignment
{
    public class TrangChuController : Controller
    {
        private readonly MobilePhoneContext db;
        public TrangChuController(MobilePhoneContext context)
        {
            db = context;
        }

        public IActionResult Index(int? id)
        {
            var listsp = db.SanPhams.AsQueryable();

            if (id.HasValue)
            {
                listsp = listsp.Where(x => x.MaLoaiSp == id.Value);
            }

            var result = listsp.Select(x => new SanPham
            {
                MaSp = x.MaSp,
                HinhSp = x.HinhSp,
                TenSp = x.TenSp,
                GiaSp = x.GiaSp,
                Chip = x.Chip,
                ManHinh = x.ManHinh,
                Ram = x.Ram,
                Rom = x.Rom,
                Soluotban = x.Soluotban,
                NgaydangSp = x.NgaydangSp
            });

            // Truyền tham số maloai vào view data để sử dụng trong view
            ViewData["MaLoai"] = id;

            return View(result);
        }
    }
}

PS36400_NguyenLocThong_Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rakkas&display=swap" rel="stylesheet">
</head>

@{
    string fullName = Context.Session.GetString("FullName");
    bool isLoggedIn = !string.IsNullOrEmpty(fullName);
}

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg sticky-md-top" id="navbar">
        <div class="container">
            <a class="navbar-brand rakkas-regular" asp-controller="TrangChu" asp-action="Index"><span id="logo-text">Mobile Shop</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span> <img src="~/image/toggle-icon.png" id="toggle-icon" /></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" asp-controller="Trangchu" asp-action="Index"><strong>Trang Chủ</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="DanhMucSP" asp-action="Index"><strong>Danh mục sản phẩm</strong></a>
                    </li>

                    @* Kiểm tra đang nhập hay chưa đn*@
                    @if (isLoggedIn)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <strong>@fullName</strong>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Login" asp-action="Logout">Đăng Xuất</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <strong>Tài Khoản</strong>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Login" asp-action="Index">Đăng Nhập</a></li>
                                <li><a class="dropdown-item" asp-controller="Register" asp-action="Index">Đăng Kí</a></li>
                            </ul>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cart" asp-action="Index"><strong>Giỏ Hàng</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="AdminPage" asp-controller="AdminTrangChu" asp-action="Index"><strong>Admin</strong></a>
                    </li>
                </ul>
                <form class="d-flex" asp-controller="TimKiemSP" asp-action="Index" method="get">
                    <input class="form-control me-2" type="search" name="timkiem" placeholder="Nhập từ khóa sản phẩm">
                    <button class="btn btn-success" type="submit">Tìm</button>
                </form>
            </div>
        </div>
    </nav>
    

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- FOOTER -->
    <div class="container bg-light text-dark mt-3 pt-3">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-5 col-sm-8 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">THÔNG TIN CỬA HÀNG</h5>
                <p class="mb-2"><i class="text-dark bi-house mr-3"></i> 123 Nguyễn Trãi, TP.HCM</p>
                <p class="mb-2"><i class="text-dark bi-telephone mr-3"></i> abc@gmail.com</p>
                <p class="mb-0"><i class="text-dark bi-envelope mr-3"></i> +012 345 67890</p>
            </div>
            <div class="col-lg-7 col-md-12">
                <div class="row">
                    <div class="col-md-5 col-sm-8 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Danh mục</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2"><i class=" mr-2"></i>Trang Chủ</a>
                            <a class="text-dark mb-2"><i class=" mr-2"></i>Giới Thiệu</a>
                            <a class="text-dark mb-2"><i class=" mr-2"></i>Liên Hệ</a>
                            <a class="text-dark mb-2"><i class=" mr-2"></i>Thanh Toán</a>
                        </div>
                    </div>
                    <div class="col-md-7 col-sm-8 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Theo Dõi Chúng Tôi Tại</h5>
                        <div class="d-flex">
                            <a class="text-dark " style="margin-right: 15px;">
                                <span><img src="~/image/facebook-icon.png"/></span>
                            </a>
                            <a class="text-dark " style="margin-right: 15px;">
                                <span><img src="~/image/instagram-icon.png" /></span>
                            </a>
                            <a class="text-dark">
                                <span><img src="~/image/twitter-icon.png" /></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row border-top mx-xl-5 py-3" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-12 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    FPT Polytechnic &copy; 2024. Nguyễn Lộc Thông - PS36400.
                </p>
            </div>
        </div>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>