PS36400_NguyenLocThong_Assignment/Controllers/DanhMucSPController.cs
using PS36400_NguyenLocThong_Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PagedList;
using System.Collections.Generic;
using System.Drawing.Printing;

namespace _21_PS36400_NguyenLocThong_ASM.Controllers
{
    public class DanhMucSPController : Controller
    {
        private readonly MobilePhoneContext db;
        public DanhMucSPController(MobilePhoneContext context)
        {
            db = context;
        }


        // Danh mục sản phẩm
        public IActionResult Index(string loai, int? id, string sortOrder, string priceRange, string screenSize,int page = 1, int pageSize = 6)
        {
            var listsp = db.SanPhams.AsQueryable();

            // Tìm MaLoaiSp tương ứng với tên loại sản phẩm
            if (!string.IsNullOrEmpty(loai))
            {
                var loaiSp = db.LoaiSanPhams.FirstOrDefault(x => x.TenLoaiSp == loai);
                if (loaiSp != null)
                {
                    id = loaiSp.MaLoaiSp;
                }
            }

            // Lọc sản phẩm theo MaLoaiSp
            if (id.HasValue)
            {
                listsp = listsp.Where(x => x.MaLoaiSp == id.Value);
            }


            ViewBag.SortNewSP = string.IsNullOrEmpty(sortOrder) ? "sanphammoi" : "sanphammoi";
            ViewBag.SortBestSeller = (sortOrder == "sanphambanchay" ? "sanphambanchay" : "sanphambanchay");
            ViewBag.SortPriceUp = (sortOrder == "giatang" ? "giatang" : "giatang");
            ViewBag.SortPriceDown = (sortOrder == "giagiam" ? "giagiam" : "giagiam");

            // Sắp xếp sản phẩm
            switch (sortOrder)
            {
                case "sanphammoi":
                    listsp = listsp.OrderByDescending(x => x.NgaydangSp);
                    break;
                case "sanphambanchay":
                    listsp = listsp.OrderByDescending(x => x.Soluotban);
                    break;
                case "giatang":
                    listsp = listsp.OrderBy(x => x.GiaSp);
                    break;
                case "giagiam":
                    listsp = listsp.OrderByDescending(x => x.GiaSp);
                    break;
                default:
                    listsp = listsp.OrderByDescending(x => x.NgaydangSp);
                    break;
            }

            // Lọc sản phẩm theo giá
            switch (priceRange)
            {
                case "down2Mil":
                    listsp = listsp.Where(x => x.GiaSp < 2000000);
                    break;
                case "2to4Mil":
                    listsp = listsp.Where(x => x.GiaSp >= 2000000 && x.GiaSp < 4000000);
                    break;
                case "4to7Mil":
                    listsp = listsp.Where(x => x.GiaSp >= 4000000 && x.GiaSp < 7000000);
                    break;
                case "up7Mil":
                    listsp = listsp.Where(x => x.GiaSp >= 7000000);
                    break;
                default:
                    break;
            }

            // Lọc sản phẩm theo kích thước màn hình
            switch (screenSize)
            {
                case "6den7inches":
                    listsp = listsp.Where(x => x.ManHinh >= 6 && x.ManHinh <= 7);
                    break;
                case "tren7inches":
                    listsp = listsp.Where(x => x.ManHinh > 7 || x.ManHinh == null);
                    break;
                default:
                    break;
            }

            var result = listsp.Select(x => new SanPham
            {
                MaSp = x.MaSp,
                HinhSp = x.HinhSp,
                TenSp = x.TenSp,
                GiaSp = x.GiaSp,
                Chip = x.Chip,
                ManHinh = x.ManHinh,
                Ram = x.Ram,
                Rom = x.Rom
            }).ToPagedList(page, pageSize);

            // Truyền tham số maloai vào view data để sử dụng trong view
            ViewData["TenLoai"] = loai;
            ViewData["SortOrder"] = sortOrder;
            ViewData["PriceRange"] = priceRange;
            ViewData["ScreenSize"] = screenSize;

            return View(result);
        }

        // Sản phẩm chi tiết
        public async Task<IActionResult> DetailProduct(int id)
        {
            var productDetail = await db.SanPhams.FirstOrDefaultAsync(p => p.MaSp == id);

            return View(productDetail);
        }


        // Phương thức cập nhật số lượt bán của sản phẩm
        public void UpdateProductSales(int productId, int quantity)
        {
            var product = db.SanPhams.Find(productId);
            if (product != null)
            {
                product.Soluotban += quantity;
                db.SaveChanges();
            }
        }

    }


}

PS36400_NguyenLocThong_Assignment/ViewComponents/MenuDanhMucSPViewComponent.cs
using PS36400_NguyenLocThong_Assignment.Models;
using Microsoft.AspNetCore.Mvc;

namespace PS36400_NguyenLocThong_Assignment.ViewComponents
{
    public class MenuDanhMucSPViewComponent : ViewComponent
    {
        private readonly MobilePhoneContext db;
        public MenuDanhMucSPViewComponent(MobilePhoneContext context) => db = context;

        public IViewComponentResult Invoke()
        {
            var data = db.LoaiSanPhams.Select(loaisp => new LoaiSanPham
            {
                MaLoaiSp = loaisp.MaLoaiSp, 
                TenLoaiSp = loaisp.TenLoaiSp
            }).OrderBy(x => x.TenLoaiSp);
            return View(data);
        }
    }
}

PS36400_NguyenLocThong_Assignment/Views/DanhMucSP/DetailProduct.cshtml
@{
    ViewData["Title"] = "DetailProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model PS36400_NguyenLocThong_Assignment.Models.SanPham

<div class="row text-center">
    <div class="col-md-5">
        <img src="~/image/@Model.HinhSp" alt="opppa18" width="400px" style="margin-top: 20px">
    </div>
    <div class="col-md-4 detail-product d-flex flex-column align-items-start justify-content-center">
        <ul class="list-detail">
            <li>
                <h2 style="font-weight:500">@Model.TenSp</h2>
            </li>
            <li class="text-danger" style="font-weight: 500; font-size: 32px">
                @String.Format("{0:N0}", Model.GiaSp)đ
            </li>
            <form asp-action="addtoCart" asp-controller="Cart" asp-route-id="@Model.MaSp">
                <li>
                    <input type="number" min="1" value="1" name="soluong" class="form-control">
                </li>
                <li class="mt-4 d-flex justify-content-center">
                    <button type="submit" class="btn btn-warning" style="width: 100%;"><span class="bi bi-basket">
                        </span>Thêm vào giỏ</button>
                </li>
            </form>
        </ul>
    </div>
    <div class="col-md-3 d-flex flex-column justify-content-center">
        <div class="st-param">
            <p style="font-size: 18px"><strong>Thông số kỹ thuật</strong></p>
            <ul style="padding-left: 30px;">
                <li>
                    <i class="bi bi-cpu" style="margin-right:8px" title="CPU"></i><p> @Model.Chip</p>
                </li>
                <li>
                    <i class="bi bi-phone" style="margin-right:8px" title="Màn hình"></i><p> @Model.ManHinh inches</p>
                </li>
                <li>
                    <i class="bi bi-memory" style="margin-right:8px" title="RAM"></i><p> @Model.Ram GB</p>
                </li>
                <li>
                    <i class="bi bi-hdd" style="margin-right:8px" title="ROM"></i><p> @Model.Rom GB</p>
                </li>
            </ul>
        </div>
    </div>
</div>
<hr class="mt-4">

PS36400_NguyenLocThong_Assignment/Views/DanhMucSP/Index.cshtml
@{
    ViewData["Title"] = "Danh Mục Sản Phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model PagedList.IPagedList<PS36400_NguyenLocThong_Assignment.Models.SanPham>
@using PagedList.Mvc;


<!-- HEADER -->
<header>
    <div class="container">
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/image/slideheader1.png" class="d-block w-100" alt="banner1">
                </div>
                <div class="carousel-item">
                    <img src="~/image/slideheader2.png" class="d-block w-100" alt="banner2">
                </div>
                <div class="carousel-item">
                    <img src="~/image/slideheader3.png" class="d-block w-100" alt="banner3">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                    data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                    data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</header>


<div class="row">
    <!-- Bộ lọc sản phẩm -->
    <div class="col-md-3 mt-4">
        <div id="sidebar">
            
            @*Menu danh mục sản phẩm*@
            @await Component.InvokeAsync("MenuDanhMucSP")


            <form asp-action="Index" asp-controller="DanhMucSP" method="get">
                <div class="filter-button">
                    <button class="btn btn-primary" type="submit">Lọc</button>
                </div>
                @* lọc theo giá sản phẩm *@
                <div class="widget wid-discouts">
                    <div class="heading"><h4 class="text-uppercase">Giá tiền</h4></div>
                    <div class="content">
                        <div class="form-check">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="priceRange" id="Radio1" value="all" checked>
                                <label class="form-check-label" for="Radio1">
                                    Tất cả
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="priceRange" id="Radio2" value="down2Mil">
                                <label class="form-check-label" for="Radio2">
                                    Dưới 2 triệu
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="priceRange" id="Radio3" value="2to4Mil">
                                <label class="form-check-label" for="Radio3">
                                    2 - 4 triệu
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="priceRange" id="Radio4" value="4to7Mil">
                                <label class="form-check-label" for="Radio4">
                                    4 - 7 triệu
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="priceRange" id="Radio5" value="up7Mil">
                                <label class="form-check-label" for="Radio5">
                                    Trên 7 triệu
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                
                @* lọc loại màn hình *@
                <div class="widget wid-discouts">
                    <div class="heading"><h4 class="text-uppercase">Màn hình</h4></div>
                    <div class="content">
                        <div class="form-check">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="screenSize" id="Radio6" value="all" checked>
                                <label class="form-check-label" for="Radio6">
                                    Tất cả
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="screenSize" id="Radio7" value="6den7inches">
                                <label class="form-check-label" for="Radio8">
                                    6 - 7 inches
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="screenSize" id="Radio8" value="tren7inches">
                                <label class="form-check-label" for="Radio9">
                                    Trên 7 inches
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="loai" value="@ViewData["TenLoai"]" />
                <input type="hidden" name="sortOrder" value="@ViewData["SortOrder"]" />
                <input type="hidden" name="priceRange" value="@ViewData["PriceRange"]" />
                <input type="hidden" name="screenSize" value="@ViewData["ScreenSize"]" />
            </form>
        </div>
    </div>



    <!-- Main content -->
    <div class="col-md-9">

        <div class="row mt-3">
            <div class="col-md-12">
                <div class="sort-link content float-end" style="margin-top: 5px;">
                    <button><a asp-action="Index" asp-controller="DanhMucSP" asp-route-loai="@ViewData["TenLoai"]" asp-route-priceRange="@ViewData["PriceRange"]" asp-route-screenSize="@ViewData["ScreenSize"]" asp-route-sortOrder="@ViewBag.SortNewSP" data-sort="sanphammoi">Sản phẩm mới nhất</a></button> 
                    <button><a asp-action="Index" asp-controller="DanhMucSP" asp-route-loai="@ViewData["TenLoai"]" asp-route-priceRange="@ViewData["PriceRange"]" asp-route-screenSize="@ViewData["ScreenSize"]" asp-route-sortOrder="@ViewBag.SortBestSeller" data-sort="sanphambanchay">Bán chạy nhất</a></button> 
                    <button><a asp-action="Index" asp-controller="DanhMucSP" asp-route-loai="@ViewData["TenLoai"]" asp-route-priceRange="@ViewData["PriceRange"]" asp-route-screenSize="@ViewData["ScreenSize"]" asp-route-sortOrder="@ViewBag.SortPriceUp" data-sort="giatang">Giá tăng</a></button> 
                    <button><a asp-action="Index" asp-controller="DanhMucSP" asp-route-loai="@ViewData["TenLoai"]" asp-route-priceRange="@ViewData["PriceRange"]" asp-route-screenSize="@ViewData["ScreenSize"]" asp-route-sortOrder="@ViewBag.SortPriceDown" data-sort="giagiam">Giá giảm</a></button>
                </div>
            </div>
        </div>

        <!-- Danh sách sản phẩm -->
        <div class="row p-3">
            @foreach (var item in Model)
            {
                <div class="col-md-4 col-sm-6 p-2">
                    <div class="card text-center">
                        <a asp-controller="DanhMucSP" asp-action="DetailProduct" asp-route-id="@item.MaSp">
                            <img class="product-image" src="~/image/@item.HinhSp">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title text-center product-name">@item.TenSp</h5>
                            <p class="card-text text-center text-danger text-giasp">
                                @String.Format("{0:N0}", @item.GiaSp)đ
                            </p>
                            <div class="cdt-product__config__param">
                                <div class="param-item">
                                    <i class="bi bi-cpu" title="CPU"></i>@item.Chip
                                </div>
                                <div class="param-item">
                                    <i class="bi bi-phone" title="Màn Hình"></i>@item.ManHinh inches
                                </div>
                                <div class="param-item">
                                    <i class="bi bi-memory" title="RAM"></i>@item.Ram GB
                                </div>
                                <div class="param-item">
                                    <i class="bi bi-hdd" title="ROM"></i>@item.Rom GB
                                </div>
                            </div>
                            <div class="btn-group d-flex justify-content-center" role="group">
                                <a asp-action="addtoCart" asp-controller="Cart" asp-route-id="@item.MaSp" class="btn btn-outline-success btn-sm">Thêm vào giỏ</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

        <!-- Phân trang -->
        <nav>
            <ul class="pagination justify-content-center">
                @if (Model.HasPreviousPage)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageNumber - 1)" asp-route-loai="@ViewData["TenLoai"]" asp-route-sortOrder="@ViewData["SortOrder"]" asp-route-screenSize="@ViewData["ScreenSize"]" asp-route-priceRange="@ViewData["PriceRange"]">Trước</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <a class="page-link">Trước</a>
                    </li>
                }
                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                        <a class="page-link" asp-action="Index" asp-route-page="@i" asp-route-loai="@ViewData["TenLoai"]" asp-route-sortOrder="@ViewData["SortOrder"]" asp-route-screenSize="@ViewData["ScreenSize"]" asp-route-priceRange="@ViewData["PriceRange"]">@i</a>
                    </li>
                }
                @if (Model.HasNextPage)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageNumber + 1)" asp-route-loai="@ViewData["TenLoai"]" asp-route-sortOrder="@ViewData["SortOrder"]" asp-route-screenSize="@ViewData["ScreenSize"]" asp-route-priceRange="@ViewData["PriceRange"]">Sau</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <a class="page-link">Sau</a>
                    </li>
                }
            </ul>
        </nav>
    </div>

</div>