PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Controllers/AdminQLLoaiSanPhamController.cs
using Microsoft.AspNetCore.Mvc;
using PS36400_NguyenLocThong_Assignment.Models;
using Microsoft.EntityFrameworkCore;

namespace PS36400_NguyenLocThong_Assignment.Areas.Admin.Controllers
{
    [Area("AdminPage")]
    [Route("Admin/{controller}/{action}")]
    public class AdminQLLoaiSanPhamController : Controller
    {
        private readonly MobilePhoneContext db;
        public AdminQLLoaiSanPhamController(MobilePhoneContext context)
        {
            db = context;
        }
        public IActionResult IndexLSP()
        {
            List<LoaiSanPham> loaisp = db.LoaiSanPhams.ToList();
            return View(loaisp);
        }

        [HttpGet]
        public IActionResult CreateLSP()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateLSP(LoaiSanPham loaiSanPham)
        {
            if (ModelState.IsValid)
            {
                db.LoaiSanPhams.Add(loaiSanPham);
                db.SaveChanges();
                return RedirectToAction("IndexLSP");
            }
            return View(loaiSanPham);
        }


        [HttpGet]
        public IActionResult EditLSP(int id)
        {
            var loaiSanPham = db.LoaiSanPhams.Find(id);
            if (loaiSanPham == null)
            {
                return NotFound();
            }
            return View(loaiSanPham);
        }


        [HttpPost]
        public IActionResult EditLSP(LoaiSanPham loaiSanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiSanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexLSP");
            }
            return View(loaiSanPham);
        }

        [HttpGet]
        public IActionResult DeleteLSP(int id)
        {
            var loaiSanPham = db.LoaiSanPhams.Find(id);
            if (loaiSanPham == null)
            {
                return NotFound();
            }
            db.LoaiSanPhams.Remove(loaiSanPham);
            db.SaveChanges();
            return RedirectToAction("IndexLSP");
        }
    }
}

PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Views/AdminQLLoaiSanPham/CreateLSP.cshtml
@model PS36400_NguyenLocThong_Assignment.Models.LoaiSanPham

@{
    ViewData["Title"] = "CreateLSP";
    Layout = "~/Areas/AdminPage/Views/Shared/_Layout.cshtml";
}

<h1>CreateLSP</h1>

<h4>LoaiSanPham</h4>
<a asp-action="IndexLSP" asp-controller="AdminQLLoaiSanPham" class="btn btn-danger">Trở về</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateLSP" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenLoaiSp" class="control-label"></label>
                <input asp-for="TenLoaiSp" class="form-control" />
                <span asp-validation-for="TenLoaiSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button class="btn btn-primary mr-1" type="submit">Thêm</button>
            </div>
        </form>
    </div>
</div>

PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Views/AdminQLLoaiSanPham/EditLSP.cshtml
@model PS36400_NguyenLocThong_Assignment.Models.LoaiSanPham

@{
    ViewData["Title"] = "EditLSP";
    Layout = "~/Areas/AdminPage/Views/Shared/_Layout.cshtml";
}

<h1>Sửa Loại Sản Phẩm</h1>

<a asp-action="IndexLSP" asp-controller="AdminQLLoaiSanPham" class="btn btn-danger">Trở về</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditLSP" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaLoaiSp" />
            <div class="form-group">
                <label asp-for="TenLoaiSp" class="control-label"></label>
                <input asp-for="TenLoaiSp" class="form-control" />
                <span asp-validation-for="TenLoaiSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button class="btn btn-primary mr-1" type="submit">Sửa</button>
            </div>
        </form>
    </div>
</div>

PS36400_NguyenLocThong_Assignment/Areas/AdminPage/Views/AdminQLLoaiSanPham/IndexLSP.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminPage/Views/Shared/_Layout.cshtml";
}

@model List<PS36400_NguyenLocThong_Assignment.Models.LoaiSanPham>


@if (!string.IsNullOrEmpty(ViewBag.AlertMessage))
{
    <script>
        alert("@ViewBag.AlertMessage");
    </script>
}


<div class="section-body">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h2>Quản Lí Loại Sản Phẩm</h2>
            </div>
            <div class="col-sm-12 col-md-12">
                <a asp-action="CreateLSP" asp-controller="AdminQLLoaiSanPham" class="btn btn-primary">Thêm loại sản phẩm mới</a>
            </div>
            <div class="card-body">
                <table class="table" id="product-table">
                    <thead>
                        <tr style="text-align: center;">
                            <th scope="col">Mã Loại Sản Phẩm</th>
                            <th scope="col">Tên Loại Sản Phẩm</th>
                            <th scope="col">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                            <tr style="text-align: center;">
                                <th scope="row">@item.MaLoaiSp</th>
                                <td>@item.TenLoaiSp</td>
                                <td>
                                    <a asp-action="EditLSP" asp-controller="AdminQLLoaiSanPham" asp-route-id="@item.MaLoaiSp" class="btn btn-primary">Sửa</a>
                                    <a asp-action="DeleteLSP" asp-controller="AdminQLLoaiSanPham" asp-route-id="@item.MaLoaiSp" class="btn btn-danger">Xóa </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>